[ollama]
base_url = "http://localhost:11435"
request_timeout = 300  # in seconds

[llm]
# model = "gemma3:12b"
model = "gemma3:latest"
temperature = 0.75
topk = 40

[embedding]
# model = "mxbai-embed-large:latest"
# model = "embeddinggemma:latest"
model = "bge-m3:latest"

[query_engine]
top_k = 5
# possible values: "tree_summarize", "refine", "compact", "simple_summarize", "accumulate", "compact_accumulate"
response_mode = "tree_summarize"
